volumes:
  pgdata:
    name: bulba_pgdata
  rabbitmq_data:
    name: esd_rabbitmq_data
    # external: true

networks:
  bulba-net:
      driver: bridge
      name: bulba-net

services:

  #######################################
  # Kong API Gateway
  #######################################
  kong:
    image: kong/kong-gateway:3.9
    restart: always
    networks:
      - bulba-net
    environment:
      KONG_DATABASE: "off" # Enable DB-less mode.
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yaml # Path to declarative config.
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
    ports:
      - "8000:8000" # Proxy port for APIs.
      - "8001:8001" # Admin API port.
      - "8002:8002" # Kong Manager GUI port.
    volumes:
      - ./kong.yaml:/etc/kong/kong.yaml # Mount kong.yaml into container.

  #######################################
  # Flask Microservices (Bidding, Marketplace, Inventory)
  #######################################

  # Bidding
  bidding-service:
    build:
      context: ../backend/bidding/
    container_name: bidding-service
    restart: always
    networks:
      - bulba-net
    env_file:
      - ../backend/bidding/.env  # Load environment variables from .env file
    ports:
      - "5002:5002"
    depends_on:
      - rabbitmq-setup


  # Inventory
  inventory-service:
    build:
      context: ../backend/inventory/
    container_name: inventory-service
    restart: always
    networks:
      - bulba-net
    env_file:
      - ../backend/inventory/.env  # Load environment variables from .env file
    ports:
      - "5003:5003"

  # Marketplace
  marketplace-service:
    build:
      context: ../backend/marketplace/
    container_name: marketplace-service
    restart: always
    networks:
      - bulba-net
    env_file:
      - ../backend/marketplace/.env  # Load environment variables from .env file
    ports:
      - "5004:5004"
    depends_on:
      - redis-cache-service


  # Grading
  grading-service:
    build:
      context: ../backend/grading/
    container_name: grading-service
    restart: always
    networks:
      - bulba-net
    # env_file:
      # - ../backend/grading/.env  # Load environment variables from .env file
    ports:
      - "5005:5005"
    depends_on:
      - rabbitmq-setup

  # External Grading
  external-grading-service:
    build:
      context: ../backend/external_grading/
    container_name: external-grading-service
    restart: always
    networks:
      - bulba-net
    # env_file:
      # - ../backend/external_grading/.env  # Load environment variables from .env file
    ports:
      - "5006:5006"
    depends_on:
      - rabbitmq-setup

  # Delivery
  delivery-service:
    build:
      context: ../backend/delivery/
    container_name: delivery-service
    restart: always
    networks:
      - bulba-net
    # env_file:
      # - ../backend/delivery/.env  # Load environment variables from .env file
    ports:
      - "5007:5007"
    depends_on:
      - rabbitmq-setup

  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    build: ../backend/rabbitmq
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - "5672:5672" # RabbitMQ Client Connection
      - "15672:15672" # RabbitMQ Management UI
      - "15674:15674" # RabbitMQ Websocket
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - bulba-net
    healthcheck: 
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
      start_period: 50s
      timeout: 5s

  rabbitmq-setup:
    build: ../backend/rabbitmq_setup
    container_name: amqp-setup
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - bulba-net

  #######################################
  # Redis Cache (For Bidding Microservice)
  #######################################
  redis-cache-service:
    image: redis:latest
    container_name: redis-cache-service
    restart: always
    networks:
      - bulba-net

